 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/zoos", type: :request do
  # Zoo. As you add validations to Zoo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Zoo.create! valid_attributes
      get zoos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      zoo = Zoo.create! valid_attributes
      get zoo_url(zoo)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_zoo_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      zoo = Zoo.create! valid_attributes
      get edit_zoo_url(zoo)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Zoo" do
        expect {
          post zoos_url, params: { zoo: valid_attributes }
        }.to change(Zoo, :count).by(1)
      end

      it "redirects to the created zoo" do
        post zoos_url, params: { zoo: valid_attributes }
        expect(response).to redirect_to(zoo_url(Zoo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Zoo" do
        expect {
          post zoos_url, params: { zoo: invalid_attributes }
        }.to change(Zoo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post zoos_url, params: { zoo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested zoo" do
        zoo = Zoo.create! valid_attributes
        patch zoo_url(zoo), params: { zoo: new_attributes }
        zoo.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the zoo" do
        zoo = Zoo.create! valid_attributes
        patch zoo_url(zoo), params: { zoo: new_attributes }
        zoo.reload
        expect(response).to redirect_to(zoo_url(zoo))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        zoo = Zoo.create! valid_attributes
        patch zoo_url(zoo), params: { zoo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested zoo" do
      zoo = Zoo.create! valid_attributes
      expect {
        delete zoo_url(zoo)
      }.to change(Zoo, :count).by(-1)
    end

    it "redirects to the zoos list" do
      zoo = Zoo.create! valid_attributes
      delete zoo_url(zoo)
      expect(response).to redirect_to(zoos_url)
    end
  end
end
